config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts

  devise_scope :user do

    root to: "devise/sessions#new"
  end

end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :email, type: String
  field :phone_number, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :user_id, type: Integer
  field :street, type: String
  field :street2, type: String
  field :city, type: String
  field :state, type: String
  field :zip_code, type: String
  field :contact_id, type: Integer

  belongs_to :user

# @b = Address.find_by(:contact_id => BSON::ObjectId('57964cc231c552473c000001'))

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  has_many :contacts
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && params['action'] != "edit"
      "devise_layout"
    else
      "application"
    end
  end

	def after_sign_in_path_for(resource_or_scope)
	 contacts_path
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all(:user_id => BSON::ObjectId(current_user.id))
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(BSON::ObjectId(params['id']))
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :phone_number, :first_name, :last_name, :user_id)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name' %>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name'%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email Address', required: true %>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.phone_field :phone_number, class: 'form-control', placeholder: 'Phone Number'%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.text_field :street, class: 'form-control', placeholder: 'Street'%>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.text_field :street2, class: 'form-control', placeholder: 'Street 2'%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="field">
        <%= f.text_field :city, class: 'form-control', placeholder: 'City'%>
      </div>
    </div>
    <div class="col-md-3 col-sm-3">
      <div class="field">
        <%= f.text_field :state, class: 'form-control', placeholder: 'State'%>
      </div>
    </div>
    <div class="col-md-3 col-sm-3">
      <div class="field">
        <%= f.text_field :zip_code, class: 'form-control', placeholder: 'Zipcode '%>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-md btn-primary btn-block" %>
  </div>

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="contact-wrapper">
  <div class="row">
  <% @contacts.each do |contact| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel panel-default contact-panel ">
        <div class="panel-heading">
          <%= link_to( contact.first_name + " " + contact.last_name, contact)%>
          <p><%= contact.state %></p>
        </div>
        <div class="panel-actions">
          <%= link_to(edit_contact_path(contact)) do %>
            <%= embedded_svg "edit.svg" %>
          <% end %>
          <%= link_to(contact, method: :delete, data: { confirm: 'Are you sure?' }) do %>
            <%= embedded_svg "close.svg" %>
          <% end %>
        </div>
        <div class="panel-body">
          <%= contact.email %><br/>
          <p><%= contact.phone_number %></p>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="contact-wrapper show">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="panel panel-default contact-panel ">
        <div class="panel-heading">
          <%= link_to( @contact.first_name + " " + @contact.last_name, @contact)%>
          <p><%= @contact.state %></p>
        </div>
        <div class="panel-actions">
          <%= link_to(edit_contact_path(@contact)) do %>
            <%= embedded_svg "edit.svg" %>
          <% end %>
          <%= link_to(@contact, method: :delete, data: { confirm: 'Are you sure?' }) do %>
            <%= embedded_svg "close.svg" %>
          <% end %>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <div class="contact-address">
                <%= @contact.street %>
                <%= @contact.street2 %><br/>
                <%= @contact.city %>,
                <%= @contact.state %>
                <%= @contact.zip_code %>
              </div>
            </div>
            <div class="col-md-6">
              <%= @contact.email %><br/>
              <p><%= @contact.phone_number %></p>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PeePle</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Profile', edit_user_registration_path) %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <li class="active"><%= link_to 'All Contacts', contacts_path %></li>
  <li><%= link_to 'New Contact', new_contact_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peeple</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/sidebar' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/devise_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peeple</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="col-sm-12 main">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>